import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types types -l ts -s`.

export enum UsersRole {
    ADMIN = "admin",
    CLIENT = "client"
}

export enum OrdersStatus {
    PENDING = "PENDING",
    PAID = "PAID",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED"
}

export enum PaymentsStatus {
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED"
}

export type Users = Models.Row & {
    userId: string;
    role: UsersRole;
    name: string;
    email: string;
}

export type Products = Models.Row & {
    name: string;
    price: string;
    description: string | null;
    image: string | null;
}

export type Branches = Models.Row & {
    name: string;
    isHeadquarter: boolean;
    location: string | null;
    phoneNumber: string | null;
}

export type Cart = Models.Row & {
    userId: string;
    branchId: string | null;
    items: string;
}

export type Inventory = Models.Row & {
    branchId: string;
    productId: string;
    quantityAvailable: number;
    lastRestockDate: string | null;
}

export type Restocks = Models.Row & {
    adminId: string;
    branchId: string;
    productId: string;
    quantityAdded: number;
    previousQuantity: number;
    newQuantity: number;
}

export type Orders = Models.Row & {
    userId: string;
    branchId: string;
    totalAmount: string;
    status: OrdersStatus;
    paidAt: string | null;
}

export type Payments = Models.Row & {
    orderId: string;
    mpesaReceiptNumber: string | null;
    phoneNumber: string;
    amount: string;
    status: PaymentsStatus;
    mpesaCheckoutRequestId: string | null;
    transactionDate: string | null;
    errorMessage: string | null;
}

export type OrderItems = Models.Row & {
    orderId: string;
    productId: string;
    quantity: number;
    unitPrice: string;
    subtotal: string;
}
